version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mercadogratis
      - MYSQL_USER=mercado
      - MYSQL_PASSWORD=mercado
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
  api:
    container_name: api
    image: spring-boot-api-tutorial-img
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    restart: always   

volumes:
  mysqldb: