@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title "Mercadogratis - Component View"

LAYOUT_TOP_DOWN()

Container(webapp, "Web Application", "Angular", "Main interaction with Application")

ContainerDb(db, "Database", "MySQL", "Stores all entities and information")


Container_Boundary(api, "API Application") {

    Component(login, "Login Controller", "Spring RestController", "Allows users to sign in")

    Component(productCtrl, "Products Controller", "Spring RestController", "Provides Product CRUD")

    Component(productSvc, "Products Service", "Spring Bean", "Provides functionality related to products.")
    Component(loginSvc, "Login Service", "Spring Bean", "Provides functionality related to authentication.")


    Rel(productCtrl, productSvc, "uses")
    Rel(login, loginSvc, "uses")

    Rel(productSvc, db, "Read & write [JDBC]")
    Rel(loginSvc, db, "Read & write [JDBC]")
}

Rel(webapp, productCtrl, "uses", "JSON HTTPS")
Rel(webapp, login, "uses", "JSON HTTPS")


@enduml