@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/mysql.puml
!include FONTAWESOME/users.puml

title "Mercadogratis - Container view"

LAYOUT_TOP_DOWN()

Component_Ext(public_api, "Gateway heroku", "HTTPS")
System_Ext(gmail, "OAuth2 Google")


System_Boundary(system, "System"){
	System_Boundary(app_fe, "Frontend"){
	    Component(angular, "Client side App", "Angular", $sprite="angular")
	}
	System_Boundary(app_be, "Backend"){
	    Component(backend, "Backend", "Java", $sprite="java")
	    ComponentDb(mysql,"MySQL", "Items schema", $sprite="mysql")
	}
}

Rel(public_api, angular, "Uses", "https")
Rel_Right(angular, gmail, "auth")
Rel(angular, backend, "Uses", "https")
Rel(backend, mysql, "Read/Write")
@enduml