@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

title "Mercadogratis - Context view"

LAYOUT_TOP_DOWN()

Person(users, "Users", "Buyers/Sellers", $sprite="users")


System(system, "Mercadogratis", "Marketplace for search, buy and sell items")
System_Ext(gmail, "OAuth2 Google")

Rel(users, system, "uses")

Rel_Right(system, gmail, "auth", "http")


@enduml