@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor client

box Spring BE
control ProductController
participant ProductService
participant ProductRepository
end box
database DB

client -> ProductController: POST product
ProductController -> ProductController: validate
ProductController -> ProductService: save
ProductService -> ProductRepository: save
ProductRepository -> DB : INSERT/UPDATE product
DB -> ProductRepository : ok
ProductRepository -> ProductService : saved product
ProductService -> ProductController : saved product
ProductController -> client : JSON saved product

@enduml